library(igraph)
nodes <- read.csv("new_file_nodes_1000.csv", header=T, as.is=T)
links <- read.csv("new_file_nodup_1000.csv", header=T, as.is=T)
net <- graph_from_data_frame(d=links, vertices=nodes, directed=T)
sink("degree.txt")
degree(net)
sink()
sink("closeness.txt")
closeness(net)
sink()
sink("eigen_centrality.txt")
eigen_centrality(net)$vector
sink()
sink("betweenness.txt")
betweenness(net)
sink()

